<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKhachSan" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-LGNFL6U6;Initial Catalog=QuanLyKhachSan;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyKhachSanConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDichVu" Member="ChiTietDichVus">
    <Type Name="ChiTietDichVu">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDichVu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DichVu_ChiTietDichVu" Member="DichVu" ThisKey="maDichVu" OtherKey="maDichVu" Type="DichVu" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietDichVu" Member="HoaDon" ThisKey="maHD" OtherKey="maHD" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="maPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenPhong" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maLoai" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="hinhAnh" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="giaPhong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="giamGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="danhGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Phong_HoaDon" Member="HoaDons" ThisKey="maPhong" OtherKey="maPhong" Type="HoaDon" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="maLoai" OtherKey="maLoai" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaCV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ChucVu_NhanVien" Member="NhanViens" ThisKey="MaCV" OtherKey="MaCV" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="maDichVu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenDichVu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="giaTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DichVu_ChiTietDichVu" Member="ChiTietDichVus" ThisKey="maDichVu" OtherKey="maDichVu" Type="ChiTietDichVu" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="maHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="tenPhong" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="maPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tienThanhToan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietDichVu" Member="ChiTietDichVus" ThisKey="maHD" OtherKey="maHD" Type="ChiTietDichVu" />
      <Association Name="Phong_HoaDon" Member="Phong" ThisKey="maPhong" OtherKey="maPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="maNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="maKH" OtherKey="maKH" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="maLoai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenlp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="maLoai" OtherKey="maLoai" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi_NV" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT_NV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="maNV" Type="HoaDon" />
      <Association Name="ChucVu_NhanVien" Member="ChucVu" ThisKey="MaCV" OtherKey="MaCV" Type="ChucVu" IsForeignKey="true" />
    </Type>
  </Table>
</Database>